[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "QConfig"
version = "0.0.1"
authors = [
  { name="Kenny Hommel", email="kennyhommel36@gmail.com" },
]
description = "A helper package to store and load PyQt GUI configurations"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/kennyhml/QConfig"
"Bug Tracker" = "https://github.com/kennyhml/QConfig/issues"